Change Language Selection(#1017)
Swati4star/Images-to-PDF pull request #1024
Opened 2021-09-03 17:04 UTC by Muskan7Tripathi

# Description

Application for language selection option in this app.

Fixes (#1017 )

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
![SS IMAGE](https://user-images.githubusercontent.com/89143862/132042010-ff3001bb-8ddc-48d1-90a0-a9fa8dc981ac.jpg)
![ss](https://user-images.githubusercontent.com/89143862/132042025-f5432bf1-22d7-41e1-8be3-bbae33dbb6cf.jpg)
[Language selection.zip](https://github.com/Swati4star/Images-to-PDF/files/7107489/Language.selection.zip)

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-09-04 16:56 UTC, Swati4star commented
@Muskan7Tripathi - There are merge conflicts in this PR. resolve those also.

2021-09-04 16:59 UTC, Swati4star requested changes
There are 231 file chnages in this PR. Can you do a self review and check if all these are necessary for your feature?

2021-09-04 16:59 UTC, Swati4star commented on README.md
> -<a href="https://www.buymeacoff.ee/WmJepqz6H" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: auto !important;widt
why have you removed this?

2021-09-04 16:59 UTC, Swati4star commented on .travis.yml
> +    - build-tools-30.0.3
are these changes needed for your change? why?

2021-09-04 16:59 UTC, Swati4star commented on app/proguard-rules.pro
> +-dontwarn com.squareup.picasso.**
why this change?

2021-09-04 16:59 UTC, Swati4star commented on app/build.gradle
> +    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
Is there a need to update these?

2021-09-04 16:59 UTC, Swati4star commented on app/src/androidTest/java/swati4star/createpdf/util/ImageUtilsTest.java
> +package swati4star.createpdf.util;
why have you added this file?

2021-09-25 13:55 UTC, berlin4apk commented
Sorry but For me, this PR don't look right!

Can you please split it to different clean new PRs?

2021-11-19 11:56 UTC, closed without merging