Enhancement on Application
Swati4star/Images-to-PDF pull request #915
Opened 2020-07-16 11:39 UTC by maharishi1

Added the left out items:
2. Search functionality inside FAQ
3. Add Chinese translation for Simplified Chinese (Singapore)

Resolves: #884 

Screenshots:- https://drive.google.com/file/d/1WO0XZb4hEGX7_D52GnBPaKlkp7ZAVoCT/view?usp=drivesdk
            https://drive.google.com/file/d/1WHUY_UMPgaF3hlKByqsZ7bCSrcFxQO3c/view?usp=drivesdk

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Run the app and go to FAQ section.

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2020-07-16 18:23 UTC, Swati4star commented on app/src/main/res/layout/fragment_faq.xml
> +<!--    <FrameLayout-->
Remove the commented part.
Add a screenshot of layout with the changes

2020-07-16 18:24 UTC, Swati4star commented on app/src/main/res/layout/fragment_faq.xml
> +         android:hint="search....."/>
Don't add strings as constant here. Add them to strings.xml file

2020-07-17 03:45 UTC, maharishi1 commented
![Screenshot from 2020-07-17 08-38-16](https://user-images.githubusercontent.com/42871956/87746340-f217d680-c80d-11ea-88e7-8f542ca85b5a.png)

2020-10-01 04:17 UTC, Swati4star commented
It is not preferable to have 2 different type of changes in single PR. Can you share different PRs for your changes ? @maharishi1

2020-10-01 04:17 UTC, Swati4star commented on app/src/main/java/swati4star/createpdf/adapter/FAQAdapter.java
> +     * @param position  - view position
remove the formatting changes from this file

2020-10-01 04:17 UTC, Swati4star commented on app/src/main/java/swati4star/createpdf/fragment/FAQFragment.java
> +
why these extra lines?

2020-10-01 04:18 UTC, Swati4star commented on app/src/main/java/swati4star/createpdf/fragment/FAQFragment.java
> +
not needed

2020-10-01 04:18 UTC, Swati4star requested changes

2020-10-01 04:18 UTC, Swati4star commented on app/src/main/res/layout/fragment_faq.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
You can revert this file

2020-10-01 04:18 UTC, Swati4star commented on app/src/main/res/values/strings.xml
> +    <!--  About US & App Description & Contact US  -->
revert not required changes

2020-10-13 05:05 UTC, Swati4star commented
Closing due to inactivity

2020-10-13 05:05 UTC, closed without merging